# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventcrear.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Crear_Sesion(object):
    def setupUi(self, Crear_Sesion):
        Crear_Sesion.setObjectName("Crear_Sesion")
        Crear_Sesion.resize(611, 501)
        Crear_Sesion.setMinimumSize(QtCore.QSize(611, 501))
        Crear_Sesion.setMaximumSize(QtCore.QSize(611, 501))
        self.divmarco = QtWidgets.QFrame(Crear_Sesion)
        self.divmarco.setGeometry(QtCore.QRect(0, 0, 611, 51))
        self.divmarco.setStyleSheet("background-color: rgb(36, 41, 46);")
        self.divmarco.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.divmarco.setFrameShadow(QtWidgets.QFrame.Raised)
        self.divmarco.setObjectName("divmarco")
        self.label_Milnes = QtWidgets.QLabel(self.divmarco)
        self.label_Milnes.setGeometry(QtCore.QRect(20, 0, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_Milnes.setFont(font)
        self.label_Milnes.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Milnes.setObjectName("label_Milnes")
        self.boton_crear_sesion = QtWidgets.QPushButton(self.divmarco)
        self.boton_crear_sesion.setGeometry(QtCore.QRect(480, 0, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.boton_crear_sesion.setFont(font)
        self.boton_crear_sesion.setStyleSheet("color: rgb(142, 153, 154);\n"
"border: 0px;")
        self.boton_crear_sesion.setObjectName("boton_crear_sesion")
        self.boton_iniciar_sesion = QtWidgets.QPushButton(self.divmarco)
        self.boton_iniciar_sesion.setGeometry(QtCore.QRect(360, 0, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.boton_iniciar_sesion.setFont(font)
        self.boton_iniciar_sesion.setStyleSheet("color: rgb(214, 231, 232);\n"
"border: 0px;\n"
"")
        self.boton_iniciar_sesion.setObjectName("boton_iniciar_sesion")
        self.inputedad = QtWidgets.QLineEdit(Crear_Sesion)
        self.inputedad.setGeometry(QtCore.QRect(180, 230, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.inputedad.setFont(font)
        self.inputedad.setStyleSheet("border: 1px solid rgb(112, 112, 112);\n"
"color: rgb(25, 25, 25);\n"
"background-color:rgba(226, 170, 123, .4);\n"
"border-radius: 3px 3px 3px 3px;")
        self.inputedad.setMaxLength(500)
        self.inputedad.setAlignment(QtCore.Qt.AlignCenter)
        self.inputedad.setClearButtonEnabled(True)
        self.inputedad.setObjectName("inputedad")
        self.printemail = QtWidgets.QLabel(Crear_Sesion)
        self.printemail.setGeometry(QtCore.QRect(180, 280, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.printemail.setFont(font)
        self.printemail.setStyleSheet("color:  rgb(0, 12, 60);;")
        self.printemail.setTextFormat(QtCore.Qt.PlainText)
        self.printemail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.printemail.setObjectName("printemail")
        self.printedad = QtWidgets.QLabel(Crear_Sesion)
        self.printedad.setGeometry(QtCore.QRect(180, 210, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.printedad.setFont(font)
        self.printedad.setStyleSheet("color:  rgb(0, 12, 60);")
        self.printedad.setTextFormat(QtCore.Qt.PlainText)
        self.printedad.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.printedad.setObjectName("printedad")
        self.inputnombre = QtWidgets.QLineEdit(Crear_Sesion)
        self.inputnombre.setGeometry(QtCore.QRect(180, 90, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.inputnombre.setFont(font)
        self.inputnombre.setStyleSheet("border: 1px solid rgb(112, 112, 112);\n"
"color: rgb(25, 25, 25);\n"
"background-color:rgba(226, 170, 123, .4);\n"
"border-radius: 3px 3px 3px 3px;")
        self.inputnombre.setText("")
        self.inputnombre.setMaxLength(500)
        self.inputnombre.setAlignment(QtCore.Qt.AlignCenter)
        self.inputnombre.setClearButtonEnabled(True)
        self.inputnombre.setObjectName("inputnombre")
        self.printapellido = QtWidgets.QLabel(Crear_Sesion)
        self.printapellido.setGeometry(QtCore.QRect(180, 140, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.printapellido.setFont(font)
        self.printapellido.setStyleSheet("color:  rgb(0, 12, 60);;")
        self.printapellido.setTextFormat(QtCore.Qt.PlainText)
        self.printapellido.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.printapellido.setObjectName("printapellido")
        self.printnombre = QtWidgets.QLabel(Crear_Sesion)
        self.printnombre.setGeometry(QtCore.QRect(180, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.printnombre.setFont(font)
        self.printnombre.setStyleSheet("color:  rgb(0, 12, 60);")
        self.printnombre.setTextFormat(QtCore.Qt.PlainText)
        self.printnombre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.printnombre.setObjectName("printnombre")
        self.printpassword = QtWidgets.QLabel(Crear_Sesion)
        self.printpassword.setGeometry(QtCore.QRect(180, 350, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.printpassword.setFont(font)
        self.printpassword.setStyleSheet("color:  rgb(0, 12, 60);;")
        self.printpassword.setTextFormat(QtCore.Qt.PlainText)
        self.printpassword.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.printpassword.setObjectName("printpassword")
        self.inputpassword = QtWidgets.QLineEdit(Crear_Sesion)
        self.inputpassword.setGeometry(QtCore.QRect(180, 370, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setItalic(False)
        self.inputpassword.setFont(font)
        self.inputpassword.setStyleSheet("border: 1px solid rgb(112, 112, 112);\n"
"background-color:  rgba(226, 170, 123, .4);\n"
"color: rgb(25, 25, 25);\n"
"border-radius: 3px 3px 3px 3px;r")
        self.inputpassword.setText("")
        self.inputpassword.setMaxLength(800)
        self.inputpassword.setFrame(True)
        self.inputpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputpassword.setAlignment(QtCore.Qt.AlignCenter)
        self.inputpassword.setClearButtonEnabled(True)
        self.inputpassword.setObjectName("inputpassword")
        self.inputapellidos = QtWidgets.QLineEdit(Crear_Sesion)
        self.inputapellidos.setGeometry(QtCore.QRect(180, 160, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.inputapellidos.setFont(font)
        self.inputapellidos.setStyleSheet("border: 1px solid rgb(112, 112, 112);\n"
"color: rgb(25, 25, 25);\n"
"background-color:rgba(226, 170, 123, .4);\n"
"border-radius: 3px 3px 3px 3px;")
        self.inputapellidos.setMaxLength(500)
        self.inputapellidos.setAlignment(QtCore.Qt.AlignCenter)
        self.inputapellidos.setClearButtonEnabled(True)
        self.inputapellidos.setObjectName("inputapellidos")
        self.inputemail = QtWidgets.QLineEdit(Crear_Sesion)
        self.inputemail.setGeometry(QtCore.QRect(180, 300, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.inputemail.setFont(font)
        self.inputemail.setStyleSheet("border: 1px solid rgb(112, 112, 112);\n"
"color: rgb(25, 25, 25);\n"
"background-color:rgba(226, 170, 123, .4);\n"
"border-radius: 3px 3px 3px 3px;")
        self.inputemail.setMaxLength(500)
        self.inputemail.setAlignment(QtCore.Qt.AlignCenter)
        self.inputemail.setClearButtonEnabled(True)
        self.inputemail.setObjectName("inputemail")
        self.botosiguiente = QtWidgets.QPushButton(Crear_Sesion)
        self.botosiguiente.setGeometry(QtCore.QRect(240, 430, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.botosiguiente.setFont(font)
        self.botosiguiente.setStyleSheet("background-color: rgba(36, 41, 46, .9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px 5px 5px 5px;")
        self.botosiguiente.setObjectName("botosiguiente")
        self.imagen = QtWidgets.QLabel(Crear_Sesion)
        self.imagen.setGeometry(QtCore.QRect(0, 50, 611, 451))
        self.imagen.setText("")
        self.imagen.setObjectName("imagen")
        self.imagen.raise_()
        self.divmarco.raise_()
        self.inputedad.raise_()
        self.printemail.raise_()
        self.printedad.raise_()
        self.inputnombre.raise_()
        self.printapellido.raise_()
        self.printnombre.raise_()
        self.printpassword.raise_()
        self.inputpassword.raise_()
        self.inputapellidos.raise_()
        self.inputemail.raise_()
        self.botosiguiente.raise_()

        self.retranslateUi(Crear_Sesion)
        QtCore.QMetaObject.connectSlotsByName(Crear_Sesion)
        Crear_Sesion.setTabOrder(self.inputnombre, self.inputapellidos)
        Crear_Sesion.setTabOrder(self.inputapellidos, self.inputedad)
        Crear_Sesion.setTabOrder(self.inputedad, self.inputemail)
        Crear_Sesion.setTabOrder(self.inputemail, self.inputpassword)
        Crear_Sesion.setTabOrder(self.inputpassword, self.boton_iniciar_sesion)
        Crear_Sesion.setTabOrder(self.boton_iniciar_sesion, self.boton_crear_sesion)
        Crear_Sesion.setTabOrder(self.boton_crear_sesion, self.botosiguiente)

    def retranslateUi(self, Crear_Sesion):
        _translate = QtCore.QCoreApplication.translate
        Crear_Sesion.setWindowTitle(_translate("Crear_Sesion", "Minles"))
        self.label_Milnes.setText(_translate("Crear_Sesion", "Milnes"))
        self.boton_crear_sesion.setText(_translate("Crear_Sesion", "Crear Sesión"))
        self.boton_iniciar_sesion.setText(_translate("Crear_Sesion", "Iniciar Sesión"))
        self.inputedad.setPlaceholderText(_translate("Crear_Sesion", "Introduce Tu Edad"))
        self.printemail.setText(_translate("Crear_Sesion", "Email:"))
        self.printedad.setText(_translate("Crear_Sesion", "Edad:"))
        self.inputnombre.setPlaceholderText(_translate("Crear_Sesion", "Introduce Tu Nombre"))
        self.printapellido.setText(_translate("Crear_Sesion", "Apellidos:"))
        self.printnombre.setText(_translate("Crear_Sesion", "Nombre:"))
        self.printpassword.setText(_translate("Crear_Sesion", "Password:"))
        self.inputpassword.setPlaceholderText(_translate("Crear_Sesion", "Introduce Contraseña"))
        self.inputapellidos.setPlaceholderText(_translate("Crear_Sesion", "Introduce Tus Apellidos"))
        self.inputemail.setPlaceholderText(_translate("Crear_Sesion", "Introduce Email"))
        self.botosiguiente.setText(_translate("Crear_Sesion", "Siguiente"))

