# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicio.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Inicio(object):
    def setupUi(self, Inicio):
        Inicio.setObjectName("Inicio")
        Inicio.resize(666, 427)
        Inicio.setMinimumSize(QtCore.QSize(666, 371))
        Inicio.setMaximumSize(QtCore.QSize(666, 427))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Inicio.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(20)
        Inicio.setFont(font)
        self.marco = QtWidgets.QFrame(Inicio)
        self.marco.setGeometry(QtCore.QRect(0, 0, 671, 51))
        self.marco.setStyleSheet("background-color: #F5F5F5")
        self.marco.setFrameShape(QtWidgets.QFrame.Panel)
        self.marco.setFrameShadow(QtWidgets.QFrame.Raised)
        self.marco.setLineWidth(1)
        self.marco.setObjectName("marco")
        self.printLogotipo = QtWidgets.QLabel(self.marco)
        self.printLogotipo.setGeometry(QtCore.QRect(20, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.printLogotipo.setFont(font)
        self.printLogotipo.setStyleSheet("color: #212121")
        self.printLogotipo.setObjectName("printLogotipo")
        self.printIconoUsuario = QtWidgets.QLabel(Inicio)
        self.printIconoUsuario.setGeometry(QtCore.QRect(510, 10, 31, 31))
        self.printIconoUsuario.setText("")
        self.printIconoUsuario.setScaledContents(True)
        self.printIconoUsuario.setObjectName("printIconoUsuario")
        self.inputUsuarioMarco = QtWidgets.QLabel(Inicio)
        self.inputUsuarioMarco.setGeometry(QtCore.QRect(540, 0, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.inputUsuarioMarco.setFont(font)
        self.inputUsuarioMarco.setStyleSheet("color: rgb(148, 148, 148);")
        self.inputUsuarioMarco.setText("")
        self.inputUsuarioMarco.setScaledContents(False)
        self.inputUsuarioMarco.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.inputUsuarioMarco.setObjectName("inputUsuarioMarco")
        self.printEmail = QtWidgets.QLabel(Inicio)
        self.printEmail.setGeometry(QtCore.QRect(30, 80, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(11)
        self.printEmail.setFont(font)
        self.printEmail.setStyleSheet("color: #444")
        self.printEmail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.printEmail.setObjectName("printEmail")
        self.inputEmail = QtWidgets.QLabel(Inicio)
        self.inputEmail.setGeometry(QtCore.QRect(80, 80, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputEmail.setFont(font)
        self.inputEmail.setStyleSheet("color:#9E9E9E")
        self.inputEmail.setText("")
        self.inputEmail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.inputEmail.setObjectName("inputEmail")
        self.botonEmail = QtWidgets.QCommandLinkButton(Inicio)
        self.botonEmail.setGeometry(QtCore.QRect(20, 70, 631, 41))
        self.botonEmail.setText("")
        icon = QtGui.QIcon.fromTheme("w")
        self.botonEmail.setIcon(icon)
        self.botonEmail.setObjectName("botonEmail")
        self.line = QtWidgets.QFrame(Inicio)
        self.line.setGeometry(QtCore.QRect(20, 100, 631, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Inicio)
        self.line_2.setGeometry(QtCore.QRect(20, 60, 631, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.printPassword = QtWidgets.QLabel(Inicio)
        self.printPassword.setGeometry(QtCore.QRect(30, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(11)
        self.printPassword.setFont(font)
        self.printPassword.setStyleSheet("color: #444444")
        self.printPassword.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.printPassword.setObjectName("printPassword")
        self.inputPassword = QtWidgets.QLabel(Inicio)
        self.inputPassword.setGeometry(QtCore.QRect(110, 140, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputPassword.setFont(font)
        self.inputPassword.setStyleSheet("color:#9E9E9E")
        self.inputPassword.setText("")
        self.inputPassword.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.inputPassword.setObjectName("inputPassword")
        self.botonPassword = QtWidgets.QCommandLinkButton(Inicio)
        self.botonPassword.setGeometry(QtCore.QRect(20, 130, 631, 41))
        self.botonPassword.setText("")
        icon = QtGui.QIcon.fromTheme("w")
        self.botonPassword.setIcon(icon)
        self.botonPassword.setObjectName("botonPassword")
        self.line_3 = QtWidgets.QFrame(Inicio)
        self.line_3.setGeometry(QtCore.QRect(20, 160, 631, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Inicio)
        self.line_4.setGeometry(QtCore.QRect(20, 120, 631, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.printNombre = QtWidgets.QLabel(Inicio)
        self.printNombre.setGeometry(QtCore.QRect(30, 200, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(11)
        self.printNombre.setFont(font)
        self.printNombre.setStyleSheet("color: #444444")
        self.printNombre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.printNombre.setObjectName("printNombre")
        self.inputNombre = QtWidgets.QLabel(Inicio)
        self.inputNombre.setGeometry(QtCore.QRect(100, 200, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputNombre.setFont(font)
        self.inputNombre.setStyleSheet("color:#9E9E9E")
        self.inputNombre.setText("")
        self.inputNombre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.inputNombre.setObjectName("inputNombre")
        self.botonNombre = QtWidgets.QCommandLinkButton(Inicio)
        self.botonNombre.setGeometry(QtCore.QRect(20, 190, 631, 41))
        self.botonNombre.setText("")
        icon = QtGui.QIcon.fromTheme("w")
        self.botonNombre.setIcon(icon)
        self.botonNombre.setObjectName("botonNombre")
        self.line_5 = QtWidgets.QFrame(Inicio)
        self.line_5.setGeometry(QtCore.QRect(20, 220, 631, 21))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Inicio)
        self.line_6.setGeometry(QtCore.QRect(20, 180, 631, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.printApellidos = QtWidgets.QLabel(Inicio)
        self.printApellidos.setGeometry(QtCore.QRect(30, 260, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(11)
        self.printApellidos.setFont(font)
        self.printApellidos.setStyleSheet("color: #444444")
        self.printApellidos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.printApellidos.setObjectName("printApellidos")
        self.inputApellidos = QtWidgets.QLabel(Inicio)
        self.inputApellidos.setGeometry(QtCore.QRect(110, 260, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputApellidos.setFont(font)
        self.inputApellidos.setStyleSheet("color:#9E9E9E")
        self.inputApellidos.setText("")
        self.inputApellidos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.inputApellidos.setObjectName("inputApellidos")
        self.line_7 = QtWidgets.QFrame(Inicio)
        self.line_7.setGeometry(QtCore.QRect(20, 280, 631, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Inicio)
        self.line_8.setGeometry(QtCore.QRect(20, 240, 631, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.printEdad = QtWidgets.QLabel(Inicio)
        self.printEdad.setGeometry(QtCore.QRect(30, 320, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(11)
        self.printEdad.setFont(font)
        self.printEdad.setStyleSheet("color: #444444")
        self.printEdad.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.printEdad.setObjectName("printEdad")
        self.inputEdad = QtWidgets.QLabel(Inicio)
        self.inputEdad.setGeometry(QtCore.QRect(80, 320, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputEdad.setFont(font)
        self.inputEdad.setStyleSheet("color:#9E9E9E")
        self.inputEdad.setText("")
        self.inputEdad.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.inputEdad.setObjectName("inputEdad")
        self.botonApellidos = QtWidgets.QCommandLinkButton(Inicio)
        self.botonApellidos.setGeometry(QtCore.QRect(20, 250, 631, 41))
        self.botonApellidos.setText("")
        icon = QtGui.QIcon.fromTheme("w")
        self.botonApellidos.setIcon(icon)
        self.botonApellidos.setObjectName("botonApellidos")
        self.line_9 = QtWidgets.QFrame(Inicio)
        self.line_9.setGeometry(QtCore.QRect(20, 340, 631, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(Inicio)
        self.line_10.setGeometry(QtCore.QRect(20, 300, 631, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.botonEdad = QtWidgets.QCommandLinkButton(Inicio)
        self.botonEdad.setGeometry(QtCore.QRect(20, 310, 631, 41))
        self.botonEdad.setText("")
        icon = QtGui.QIcon.fromTheme("w")
        self.botonEdad.setIcon(icon)
        self.botonEdad.setObjectName("botonEdad")
        self.flecha5 = QtWidgets.QLabel(Inicio)
        self.flecha5.setGeometry(QtCore.QRect(620, 320, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.flecha5.setFont(font)
        self.flecha5.setText("")
        self.flecha5.setScaledContents(True)
        self.flecha5.setObjectName("flecha5")
        self.flecha4 = QtWidgets.QLabel(Inicio)
        self.flecha4.setGeometry(QtCore.QRect(620, 260, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.flecha4.setFont(font)
        self.flecha4.setText("")
        self.flecha4.setScaledContents(True)
        self.flecha4.setObjectName("flecha4")
        self.flecha3 = QtWidgets.QLabel(Inicio)
        self.flecha3.setGeometry(QtCore.QRect(620, 200, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.flecha3.setFont(font)
        self.flecha3.setText("")
        self.flecha3.setScaledContents(True)
        self.flecha3.setObjectName("flecha3")
        self.flecha2 = QtWidgets.QLabel(Inicio)
        self.flecha2.setGeometry(QtCore.QRect(620, 140, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.flecha2.setFont(font)
        self.flecha2.setText("")
        self.flecha2.setScaledContents(True)
        self.flecha2.setObjectName("flecha2")
        self.flecha1 = QtWidgets.QLabel(Inicio)
        self.flecha1.setGeometry(QtCore.QRect(620, 80, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.flecha1.setFont(font)
        self.flecha1.setText("")
        self.flecha1.setScaledContents(True)
        self.flecha1.setObjectName("flecha1")
        self.botonSalir = QtWidgets.QPushButton(Inicio)
        self.botonSalir.setGeometry(QtCore.QRect(564, 370, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botonSalir.setFont(font)
        self.botonSalir.setStyleSheet("#botonSalir{\n"
"color: rgb(237, 12, 12);\n"
"text-align: left;\n"
"background-color: rgb(250, 250, 250);\n"
"border-radius: 7px 7px 7px 7px;\n"
"border: 0px solid rgb(237, 12, 12);\n"
"}\n"
"#botonSalir::hover{\n"
"border: 2px solid rgb(237, 12, 12);\n"
"}")
        self.botonSalir.setIconSize(QtCore.QSize(26, 26))
        self.botonSalir.setObjectName("botonSalir")
        self.botonCerrarSesion = QtWidgets.QPushButton(Inicio)
        self.botonCerrarSesion.setGeometry(QtCore.QRect(20, 370, 91, 41))
        self.botonCerrarSesion.setStyleSheet("#botonCerrarSesion{\n"
"border-radius: 7px 7px 7px 7px;\n"
"border: 0px solid rgb(229, 229, 229);\n"
"}\n"
"\n"
"#botonCerrarSesion::hover{\n"
"border: 1px solid rgb(229, 229, 229);\n"
"}")
        self.botonCerrarSesion.setText("")
        self.botonCerrarSesion.setIconSize(QtCore.QSize(36, 36))
        self.botonCerrarSesion.setObjectName("botonCerrarSesion")
        self.flecha5.raise_()
        self.flecha4.raise_()
        self.flecha3.raise_()
        self.flecha2.raise_()
        self.flecha1.raise_()
        self.marco.raise_()
        self.printIconoUsuario.raise_()
        self.inputUsuarioMarco.raise_()
        self.printEmail.raise_()
        self.inputEmail.raise_()
        self.botonEmail.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.printPassword.raise_()
        self.inputPassword.raise_()
        self.botonPassword.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.printNombre.raise_()
        self.inputNombre.raise_()
        self.botonNombre.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.printApellidos.raise_()
        self.inputApellidos.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.printEdad.raise_()
        self.inputEdad.raise_()
        self.botonApellidos.raise_()
        self.line_9.raise_()
        self.line_10.raise_()
        self.botonEdad.raise_()
        self.botonSalir.raise_()
        self.botonCerrarSesion.raise_()

        self.retranslateUi(Inicio)
        QtCore.QMetaObject.connectSlotsByName(Inicio)

    def retranslateUi(self, Inicio):
        _translate = QtCore.QCoreApplication.translate
        Inicio.setWindowTitle(_translate("Inicio", "Melnis"))
        self.printLogotipo.setText(_translate("Inicio", "Melnis"))
        self.printEmail.setText(_translate("Inicio", "Email:"))
        self.printPassword.setText(_translate("Inicio", "Password:"))
        self.printNombre.setText(_translate("Inicio", "Nombre:"))
        self.printApellidos.setText(_translate("Inicio", "Apellidos:"))
        self.printEdad.setText(_translate("Inicio", "Edad:"))
        self.botonSalir.setText(_translate("Inicio", "Eliminar"))

